pipelineName: docs-appdev-merge-pipeline 
repo: pingcap/docs-appdev
defaultRef: master 
triggers:
  push:
      onBranch:
      - "master"
      - "release-*"
tasks:
    - taskName: "docs-appdev-build-pdf" 
      checkerName: "common-check" 
      params:  
        shellScript: |
          sudo pip3 install boto3
          sudo pip3 install awscli
          printf "%s\n" ${AWS_ACCESS_KEY} ${AWS_SECRET_KEY} ${AWS_REGION} "json" | aws configure
          grep -RP '\t' *  | tee | grep '.md' && exit 1; echo ok
          python3 scripts/merge_by_toc.py zh/; python3 scripts/merge_by_toc.py en/
          scripts/generate_pdf.sh
          if [ "${TARGET_BRANCH}" = "master" ]; then
            python3 scripts/upload.py output_en.pdf appdev-dev-en-manual.pdf;
            python3 scripts/upload.py output_zh.pdf appdev-dev-zh-manual.pdf;
          fi
      credentials:
        - jenkinsID: docs-cn-aws-ak
          key: AWS_ACCESS_KEY
        - jenkinsID: docs-cn-aws-sk
          key: AWS_SECRET_KEY
        - jenkinsID: docs-cn-aws-region
          key: AWS_REGION
        - jenkinsID: docs-cn-aws-bn
          key: AWS_BUCKET_NAME
        - jenkinsID: docs-cn-qiniu-ak
          key: QINIU_ACCESS_KEY
        - jenkinsID: docs-cn-qiniu-sk
          key: QINIU_SECRET_KEY
        - jenkinsID: docs-cn-qiniu-bn
          key: QINIU_BUCKET_NAME
      image: "hub.pingcap.net/jenkins/docs-cn-checker:v0.0.1"
      resources:  
          requests:
              memory: "1000Mi"
              cpu: "500m"
          limits:
              memory: "2000Mi"
              cpu: "1000m"
