pipelineName: tiflow-verify-go1.16-pipeline 
repo: pingcap/tiflow
defaultRef: master 
triggers:
  pullRequest:
      onBranch:
      - "*"
      excludeBranch:
      - "master"
      - "release-6.0"
      onComment:
      - "/verify"
      context: jenkins-ticdc/verify
tasks:
    - taskName: "tiflow-lint" 
      checkerName: "lint-check" 
      params:  
        shellScript: |
            make check
      image: "hub.pingcap.net/jenkins/centos7_golang-1.16:latest"  
      resources:  
          requests:
              memory: "1000Mi"
              cpu: "500m"
          limits:
              memory: "20000Mi"
              cpu: "20000m"

    - taskName: "tiflow-build" 
      checkerName: "build-check" 
      params:  
        shellScript: |
            make build
        outputDir : "bin/"
      image: "hub.pingcap.net/jenkins/centos7_golang-1.16:latest"  
      resources:  
          requests:
              memory: "8000Mi"
              cpu: "4000m"
          limits:
              memory: "8000Mi"
              cpu: "4000m"

    - taskName: "dm-ut" 
      checkerName: "common-check" 
      params:  
        shellScript: |
            make dm_unit_test
      image: "hub.pingcap.net/jenkins/centos7_golang-1.16:latest"  
      resources:  
          requests:
              memory: "8000Mi"
              cpu: "4000m"
          limits:
              memory: "30000Mi"
              cpu: "16000m"

    - taskName: "cdc-ut" 
      checkerName: "common-check" 
      params:  
        shellScript: |
            make unit_test
      image: "hub.pingcap.net/jenkins/centos7_golang-1.16:latest"  
      resources:  
          requests:
              memory: "8000Mi"
              cpu: "4000m"
          limits:
              memory: "30000Mi"
              cpu: "16000m"

    # - taskName: "dm-gosec" 
    #   checkerName: "gosec-check" 
    #   params:  
    #     shellScript: |
    #         gosec -fmt=junit-xml -out=results.xml -stdout -verbose=text -exclude=G103,G104,G204,G304,G307,G401,G404,G501,G505,G601 dm/... || true
    #     reportDir: results.xml
    #   image: "hub.pingcap.net/jenkins/centos7_golang-1.16:latest"  
    #   resources:  
    #       requests:
    #           memory: "2000Mi"
    #           cpu: "1000m"
    #       limits:
    #           memory: "8000Mi"
    #           cpu: "4000m"

    # - taskName: "cdc-gosec" 
    #   checkerName: "gosec-check" 
    #   params:  
    #     shellScript: |
    #         gosec -fmt=junit-xml -out=results.xml -stdout -verbose=text -exclude=G103,G104,G204,G304,G307,G401,G404,G501,G505,G601 -exclude-dir=dm ./... || true
    #     reportDir: results.xml
    #   image: "hub.pingcap.net/jenkins/centos7_golang-1.16:latest"  
    #   resources:  
    #       requests:
    #           memory: "2000Mi"
    #           cpu: "1000m"
    #       limits:
    #           memory: "8000Mi"
    #           cpu: "4000m"