pipelineName: migration-verify-pipeline 
repo: tikv/migration
defaultRef: master 
triggers:
  pullRequest:
      onBranch:
      - "master"
      - "release-*"
      - "cdc-*"
      onComment:
      - "/verify"
tasks:
    - taskName: "cdc-ut" 
      checkerName: "ut-check" 
      params:  
        shellScript: |
            cd cdc/
            make unit_test_in_verify_ci
        utReport: cdc/cdc-junit-report.xml
        covReport: cdc/cdc-coverage.xml
      image: "hub.pingcap.net/jenkins/centos7_golang-1.20:latest"
      resources:  
          requests:
              memory: "8000Mi"
              cpu: "4000m"
          limits:
              memory: "30000Mi"
              cpu: "16000m"
      credentials:
        - jenkinsID: codecov-token-tikv-migration
          key: TIKV_MIGRATION_CODECOV_TOKEN

    - taskName: "cdc-integration-test"
      checkerName: "common-check" 
      params:  
        shellScript: |
            cd cdc/
            make integration_test
      image: "hub.pingcap.net/jenkins/centos7_golang-1.20:latest"
      resources:  
          requests:
              memory: "16000Mi"
              cpu: "8000m"
          limits:
              memory: "30000Mi"
              cpu: "16000m"
      credentials:
        - jenkinsID: codecov-token-tikv-migration
          key: TIKV_MIGRATION_CODECOV_TOKEN
